// <auto-generated />
using System;
using EmployeeManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230828093256_CreatDb")]
    partial class CreatDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/51.jpg",
                            Name = "Fabian Kessler",
                            Position = 0,
                            Salary = 41218m,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/597.jpg",
                            Name = "Jared Gleason",
                            Position = 4,
                            Salary = 88845m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1222.jpg",
                            Name = "Jason Durgan",
                            Position = 7,
                            Salary = 37851m,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/849.jpg",
                            Name = "Evan Koelpin",
                            Position = 3,
                            Salary = 70084m,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/929.jpg",
                            Name = "Vicky Roberts",
                            Position = 2,
                            Salary = 33955m,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1108.jpg",
                            Name = "Shaniya Hintz",
                            Position = 2,
                            Salary = 41254m,
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/884.jpg",
                            Name = "Earnest Doyle",
                            Position = 4,
                            Salary = 80473m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/82.jpg",
                            Name = "Wallace Tillman",
                            Position = 8,
                            Salary = 76293m,
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/39.jpg",
                            Name = "Kristopher Nolan",
                            Position = 8,
                            Salary = 66368m,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/869.jpg",
                            Name = "Anne Kassulke",
                            Position = 0,
                            Salary = 88258m,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/50.jpg",
                            Name = "Liam Bergstrom",
                            Position = 6,
                            Salary = 61147m,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/678.jpg",
                            Name = "Linnie Hayes",
                            Position = 2,
                            Salary = 46522m,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/483.jpg",
                            Name = "Joana Connelly",
                            Position = 0,
                            Salary = 78963m,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/164.jpg",
                            Name = "Jeanne Turcotte",
                            Position = 7,
                            Salary = 85227m,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1188.jpg",
                            Name = "Rachel Heidenreich",
                            Position = 6,
                            Salary = 41247m,
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/671.jpg",
                            Name = "Evangeline Russel",
                            Position = 0,
                            Salary = 73221m,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/814.jpg",
                            Name = "Connor Grimes",
                            Position = 1,
                            Salary = 49194m,
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/810.jpg",
                            Name = "Humberto Labadie",
                            Position = 1,
                            Salary = 39131m,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/428.jpg",
                            Name = "Tina Goodwin",
                            Position = 1,
                            Salary = 43772m,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/52.jpg",
                            Name = "Oliver Champlin",
                            Position = 4,
                            Salary = 67578m,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1164.jpg",
                            Name = "Dolly Corwin",
                            Position = 1,
                            Salary = 79502m,
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/5.jpg",
                            Name = "Christy Jast",
                            Position = 0,
                            Salary = 75543m,
                            Type = 3
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/426.jpg",
                            Name = "Idell Wisoky",
                            Position = 8,
                            Salary = 94707m,
                            Type = 3
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/752.jpg",
                            Name = "Pietro Stehr",
                            Position = 2,
                            Salary = 41915m,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/954.jpg",
                            Name = "Luciano Kutch",
                            Position = 5,
                            Salary = 70616m,
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/187.jpg",
                            Name = "Queenie Orn",
                            Position = 7,
                            Salary = 96112m,
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/856.jpg",
                            Name = "Ashton Halvorson",
                            Position = 4,
                            Salary = 58984m,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/324.jpg",
                            Name = "Elisha Schmitt",
                            Position = 8,
                            Salary = 33526m,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/916.jpg",
                            Name = "Nona Jones",
                            Position = 6,
                            Salary = 67010m,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/383.jpg",
                            Name = "Nicholaus Cole",
                            Position = 3,
                            Salary = 98982m,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/330.jpg",
                            Name = "Nikki Kilback",
                            Position = 0,
                            Salary = 33034m,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1181.jpg",
                            Name = "Samir Mayert",
                            Position = 6,
                            Salary = 91702m,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/884.jpg",
                            Name = "Hildegard Bosco",
                            Position = 1,
                            Salary = 69652m,
                            Type = 3
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/617.jpg",
                            Name = "Destiny Schumm",
                            Position = 9,
                            Salary = 53568m,
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/975.jpg",
                            Name = "Betty Lueilwitz",
                            Position = 3,
                            Salary = 90645m,
                            Type = 2
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/766.jpg",
                            Name = "Alysson Raynor",
                            Position = 7,
                            Salary = 63872m,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/447.jpg",
                            Name = "Izaiah Veum",
                            Position = 1,
                            Salary = 54604m,
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/716.jpg",
                            Name = "Dane Denesik",
                            Position = 1,
                            Salary = 47335m,
                            Type = 3
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/197.jpg",
                            Name = "Tito Kihn",
                            Position = 3,
                            Salary = 84683m,
                            Type = 3
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/392.jpg",
                            Name = "Elliott Strosin",
                            Position = 1,
                            Salary = 63424m,
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/289.jpg",
                            Name = "Remington Fritsch",
                            Position = 3,
                            Salary = 75536m,
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/614.jpg",
                            Name = "Valerie Greenfelder",
                            Position = 6,
                            Salary = 34122m,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/386.jpg",
                            Name = "Jovanny Heathcote",
                            Position = 1,
                            Salary = 35670m,
                            Type = 3
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1008.jpg",
                            Name = "Torrance Upton",
                            Position = 5,
                            Salary = 95361m,
                            Type = 3
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/488.jpg",
                            Name = "Aletha Hauck",
                            Position = 3,
                            Salary = 91586m,
                            Type = 3
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/821.jpg",
                            Name = "Shyann Simonis",
                            Position = 3,
                            Salary = 94728m,
                            Type = 3
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/525.jpg",
                            Name = "Lenna Kuhic",
                            Position = 0,
                            Salary = 93164m,
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/810.jpg",
                            Name = "Freddie Dicki",
                            Position = 3,
                            Salary = 78897m,
                            Type = 1
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/728.jpg",
                            Name = "Aylin Deckow",
                            Position = 1,
                            Salary = 96043m,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/247.jpg",
                            Name = "Laisha Cassin",
                            Position = 7,
                            Salary = 80862m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
